name       : cppunit
version    : 1.14.0
release    : 4
source     :
    - http://dev-www.libreoffice.org/src/cppunit-1.14.0.tar.gz : 3d569869d27b48860210c758c4f313082103a5e58219a7669b52bfd29d674780
license    : LGPL-2.1
component  : programming
summary    : A C++ unit testing framework
description: |
    A C++ unit testing framework
environment: |
    export GCC_IGNORE_WERROR=1
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
