name       : cppunit
version    : 1.13.2
release    : 2
source     :
    - http://dev-www.libreoffice.org/src/cppunit/cppunit-1.13.2.tar.gz : 3f47d246e3346f2ba4d7c9e882db3ad9ebd3fcbd2e8b732f946e0e3eeb9f429f
license    : LGPL-2.1
component  : programming
summary    : A C++ unit testing framework
description: |
    A C++ unit testing framework
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
